### PR TITLE
Click to waypoint, cursor toggle and fix

### LINKED ISSUE #10: waypoint by click

### PR DESCRIPTION
**Pull request by Southland-FR**
- Added click to set waypoint (right-click on map)
- Added cursor toggle (M key) while map is open
- Added cursor and waypoint entries to help menu
- Right-click near waypoint to remove it
- Fixed division by zero in limitVectorLengthRectangle()

### CODE REVIEW

File: mradar_main_client.lua [hunk 1]
```diff
@@ -732,9 +738,9 @@ local function limitVectorLengthRectangle(x1, y1, x2, y2, xl, yl)
 	local x = x2 - x1
 	local y = y2 - y1
 
-	local k = math.min(
-		math.min(1, math.abs(xl / x)),
-		math.min(1, math.abs(yl / y)))
+	local kx = (x ~= 0) and math.min(1, math.abs(xl / x)) or 1
+	local ky = (y ~= 0) and math.min(1, math.abs(yl / y)) or 1
+	local k = math.min(kx, ky)
```
Comment (rifleh700) [inline mradar_main_client.lua]: this is unnecessary, tried it

**Comment by rifleh700** [comment]
Good! thanks!
